version: '3.7'


services:
    server:
      build:
        context: .
        dockerfile: Dockerfile
      ports:
        - "8000:8000"

    rabbitmq:
      image: rabbitmq:3-management
      ports:
        - "5672:5672"
        - "15672:15672"